apiVersion: v1
kind: Service
metadata:
  name: mp
  labels:
    app: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: mp
      port: 35353
      targetPort: 35353
      protocol: TCP
  type: ClusterIP
