apiVersion: v1
kind: Service
metadata:
  name: mp
  labels:
    game: minecraft
spec:
  selector:
    game: minecraft
    kind: controller
  ports:
    - name: mp
      port: 35353
      targetPort: 35353
      protocol: TCP
  type: ClusterIP
