version: '3'

silent: true

tasks:
  games:tf2:build:
    dir: servers/tf2/docker
    cmds:
      - docker build -t docker.io/grubertech/teamfortress2:latest .

  games:tf2:push:
    dir: servers/tf2/docker
    cmds:
      - docker build -t docker.io/grubertech/teamfortress2:latest .

  games:tf2:
    dir: servers/tf2/docker
    cmds:
      - task: games:tf2:build
      - task: games:tf2:push

  games:terraria:build:
    dir: servers/terraria/docker
    cmds:
      - task: games:terraria:go
      - docker build -t docker.io/grubertech/terraria:latest .

  games:terraria:go:
    dir: servers/terraria/docker
    cmds:
      - go mod tidy

  games:terraria:push:
    dir: servers/terraria/docker
    cmds:
      - docker build -t docker.io/grubertech/terraria:latest .

  games:terraria:
    cmds:
      - task: games:terraria:build
      - task: games:terraria:push
    ignore_error: true

  games:terraria:clean:volumes:
    cmds:
      - docker volume rm terraria_data
      - docker volume rm terraria_worlds
    ignore_error: true

  games:terraria:clean:containers:
    cmds:
      - docker container stop terraria-dedicated
      - docker container rm terraria-dedicated
    ignore_error: true

  games:terraria:test:
    cmds:
      - task: games:terraria:clean:containers
      - task: games:terraria:clean:volumes
      - |
        docker run --network=host --rm -it \
        -v terraria_worlds:/root/.local/share/Terraria/Worlds \
        -v terraria_data:/root/terraria-server \
        -e TERRARIA_AUTOSAVE_INTERVAL=5 \
        -e TERRARIA_WORLDNAME="GrubersLand" \
        -e TERRARIA_WORLDSEED="Test" \
        -e TERRARIA_MAXPLAYERS="14" \
        -e TERRARIA_USECONFIGFILE="No" \
        -e TERRARIA_PASS="N/A" \
        --name=terraria-dedicated docker.io/grubertech/terraria:latest
    ignore_error: true
