version: '3'

silent: true

env:
  VERSION: v1.1.76

tasks:
  build:
    dir: servers/factorio/image
    cmds:
      - task: go
      - docker build -t docker.io/grubertech/factorio:${VERSION} .

  deploy:gs:
    dir: servers/factorio/deploy/gs
    cmds:
      - kubectl apply -k ./

  delete:gs:
    dir: servers/factorio/deploy/gs
    cmds:
      - kubectl delete -k ./

  recreate:gs:
    cmds:
      - task: delete:gs
      - task: deploy:gs

  deploy:fleet:
    dir: servers/factorio/deploy/fleet
    cmds:
      - kubectl apply -k ./

  delete:fleet:
    dir: servers/factorio/deploy/fleet
    cmds:
      - kubectl delete -k ./

  recreate:fleet:
    cmds:
      - task: delete:fleet
      - task: deploy:fleet

  go:
    dir: servers/factorio/image
    cmds:
      - go mod tidy

  push:
    dir: servers/factorio/image
    cmds:
      - docker push docker.io/grubertech/factorio:${VERSION}

  release:
    cmds:
      - task: build
      - task: push
    ignore_error: true

  clean:volumes:
    cmds:
      - docker volume rm factorio_data
    ignore_error: true

  clean:containers:
    cmds:
      - docker container stop factorio-server
      - docker container rm factorio-server
    ignore_error: true
