version: '3'

silent: true

env:
  VERSION: v1.19.2

tasks:
  compose:
    dir: servers/minecraft/image
    cmds:
      - docker-compose down
      - docker-compose up -d --build
    ignore_error: true

  build:controller:
    dir: servers/minecraft/image/controller
    cmds:
      - docker build -t docker.io/grubertech/minecraft:controller1 .

  test:controller:
    dir: servers/minecraft/image/controller
    cmds:
      - docker run --name controller-mp-mc --rm -it -p 9001:9001 -p 9002:9002 docker.io/grubertech/minecraft:latest

  build:worker:
    dir: servers/minecraft/image/worker
    cmds:
      - docker build -t docker.io/grubertech/minecraft:${VERSION} .

  test:worker:
    dir: servers/minecraft/image/worker
    cmds:
      - docker run --name worker-mp-mc --rm -v -it docker.io/grubertech/minecraft:${VERSION}

  deploy:
    dir: servers/minecraft/deploy
    cmds:
      - kubectl apply -k ./

  destroy:
    dir: servers/minecraft/deploy
    cmds:
      - kubectl delete -k ./

  recreate:controller:
    cmds:
      - task: delete:controller
      - task: deploy:controller

  deploy:worker:
    dir: servers/minecraft/agones/deploy/worker
    cmds:
      - kubectl apply -k ./

  delete:worker:
    dir: servers/minecraft/agones/deploy/worker
    cmds:
      - kubectl delete -k ./

  recreate:worker:
    cmds:
      - task: deploy:worker

  go:
    dir: servers/minecraft/image
    cmds:
      - go mod tidy

  push:controller:
    cmds:
      - docker push docker.io/grubertech/minecraft:controller1

  push:worker:
    cmds:
      - docker push docker.io/grubertech/minecraft:${VERSION}

  release:controller:
    cmds:
      - task: build:controller
      - task: push:controller

    ignore_error: true

  release:worker:
    cmds:
      - task: build:worker
      - task: push:worker
    ignore_error: true
