version: '3'

silent: true

tasks:
  build:
    dir: servers/tf2/docker
    cmds:
      - docker build -t docker.io/grubertech/teamfortress2:latest .

  push:
    dir: servers/tf2/docker
    cmds:
      - docker build -t docker.io/grubertech/teamfortress2:latest .

  default:
    dir: servers/tf2/docker
    cmds:
      - task: tf2:build
      - task: tf2:push
