version: '3'

silent: true

env:
  TERRARIA_VERSION: v1.4.4.9

tasks:
  build:
    dir: servers/terraria/image
    cmds:
      - task: go
      - docker build -t docker.io/${DOCKER_USERNAME}/terraria:${TERRARIA_VERSION} .
      - docker build -t ghcr.io/${GITHUB_USERNAME}/terraria:${TERRARIA_VERSION} .

  docker:login:
    cmds:
      - echo "${DOCKER_TOKEN}" | docker login --username ${DOCKER_USERNAME} --password-stdin docker.io

  github:login:
    cmds:
      - echo "${GITHUB_TOKEN}" | docker login --username ${GITHUB_USERNAME} --password-stdin ghcr.io

  deploy:gs:
    dir: servers/terraria/deploy/gs
    cmds:
      - kubectl apply -k ./

  delete:gs:
    dir: servers/terraria/deploy/gs
    cmds:
      - kubectl delete -k ./

  recreate:gs:
    cmds:
      - task: delete:gs
      - task: deploy:gs

  deploy:fleet:
    dir: servers/terraria/deploy/fleet
    cmds:
      - kubectl apply -k ./

  destroy:fleet:
    dir: servers/terraria/deploy/fleet
    cmds:
      - kubectl delete -k ./

  recreate:fleet:
    cmds:
      - task: destroy:fleet
      - task: deploy:fleet

  go:
    dir: servers/terraria/image
    cmds:
      - go mod tidy

  push:
    dir: servers/terraria/image
    cmds:
      - task: docker:login
      - docker push docker.io/${DOCKER_USERNAME}/terraria:${TERRARIA_VERSION}
      - task: github:login
      - docker push ghcr.io/${GITHUB_USERNAME}/terraria:${TERRARIA_VERSION}

  release:
    cmds:
      - task: build
      - task: push
    ignore_error: true

  clean:volumes:
    cmds:
      - docker volume rm terraria_data
      - docker volume rm terraria_worlds
    ignore_error: true

  clean:containers:
    cmds:
      - docker container stop terraria-dedicated
      - docker container rm terraria-dedicated
    ignore_error: true

  test:
    cmds:
      - task: clean:containers
      - task: clean:volumes
      - |
        docker run --network=host --rm -it \
        -v terraria_worlds:/root/.local/share/Terraria/Worlds \
        -e TERRARIA_WORLDNAME="GrubersLand" \
        -e TERRARIA_WORLDSEED="Test" \
        -e TERRARIA_USECONFIGFILE="Yes" \
        -e TERRARIA_PASS="" \
        --name=terraria-dedicated docker.io/grubertech/terraria:${TERRARIA_VERSION}
    ignore_error: true
