apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: factorio-autoscaler
  labels:
    game: factorio
spec:
  fleetName: factorio
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 1
      maxReplicas: 5
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 60
