apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
metadata:
  name: terraria-policy
  labels:
    game: terraria
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: terraria-vanilla
      gameServerState: Ready
      players:
        minAvailable: 0
        maxAvailable: 1
