apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
metadata:
  name: terraria-policy
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: terraria-vanilla
      players:
        minAvailable: 0
        maxAvailable: 16
    - matchLabels:
        agones.dev/fleet: terraria-vanilla
    - matchLabels:
        game: terraria
      gameServerState: Ready
      players:
        minAvailable: 0
        maxAvailable: 16
  scheduling: Packed
  metadata:
    labels:
      game: terraria

