apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: terraria-vanilla
  labels:
    game: terraria
spec:
  replicas: 1
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        game: terraria
    spec:
      container: terraria-vanilla-fleet
      eviction:
        safe: Always
      ports:
      - name: default
        portPolicy: Dynamic
        container: terraria-vanilla-fleet
        containerPort: 7777
        protocol: TCP
      health:
        disabled: false
        initialDelaySeconds: 200
        periodSeconds: 5
        failureThreshold: 3
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      players:
        initialCapacity: 16
      template:
        metadata:
          labels:
            game: terraria
        spec:
          containers:
            - name: terraria-vanilla-fleet
              image: docker.io/grubertech/terraria:v1.4.4.9
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: terraria-cm
              ports:
                - name: gate
                  containerPort: 7777
                  protocol: TCP
              resources:
                requests:
                  cpu: 250m
                  memory: 512Mi
                limits:
                  cpu: 2000m
                  memory: 2Gi
              volumeMounts:
                - name: config-volume
                  mountPath: /server/Linux/serverconfig.txt
                  subPath: serverconfig.txt
                - name: worlds-data
                  mountPath: /root/.local/share/Terraria/Worlds
          volumes:
            - name: config-volume
              configMap:
                name: terraria-cm
            - name: worlds-data
              ephemeral:
                volumeClaimTemplate:
                  metadata:
                    labels:
                      game: terraria
                  spec:
                    accessModes: ["ReadWriteOncePod"]
                    resources:
                      requests:
                        storage: 2Gi
