apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: terraria-vanilla
spec:
  # the number of GameServers to keep Ready or Allocated in this Fleet
  replicas: 4
  scheduling: Packed
  strategy:
    # The replacement strategy for when the GameServer template is changed. Default option is "RollingUpdate",
    # "RollingUpdate" will increment by maxSurge value on each iteration, while decrementing by maxUnavailable on each
    # iteration, until all GameServers have been switched from one version to another.
    # "Recreate" terminates all non-allocated GameServers, and starts up a new set with the new details to replace them.
    type: RollingUpdate
    # Only relevant when `type: RollingUpdate`
    rollingUpdate:
      # the amount to increment the new GameServers by. Defaults to 25%
      maxSurge: 25%
      # the amount to decrements GameServers by. Defaults to 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        game: terraria
    spec:
      container: terraria-vanilla-fleet
      ports:
      - name: default
        portPolicy: Dynamic
        container: terraria-vanilla-fleet
        containerPort: 7777
        protocol: TCP
      health:
        disabled: false
        initialDelaySeconds: 200
        periodSeconds: 5
        failureThreshold: 3
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      players:
        initialCapacity: 16
      template:
        metadata:
          labels:
            app: terraria
        spec:
          containers:
            - name: terraria-vanilla-fleet
              image: docker.io/grubertech/terraria:latest
              envFrom:
                - configMapRef:
                    name: terraria-cm
              ports:
                - name: gate
                  containerPort: 7777
                  protocol: TCP
              resources:
                requests:
                  cpu: 250m
                  memory: 512Mi
                limits:
                  cpu: 2000m
                  memory: 2Gi
              volumeMounts:
                - name: config-volume
                  mountPath: /server/Linux/serverconfig.txt
                  subPath: serverconfig.txt
                - name: worlds-data
                  mountPath: /root/.local/share/Terraria/Worlds
          volumes:
            - name: config-volume
              configMap:
                name: terraria-cm
            - name: worlds-data
              persistentVolumeClaim:
                claimName: terraria-fleet-worlds
