apiVersion: v1
kind: Service
metadata:
  name: terraria
  labels:
    game: terraria
  annotations:
    tailscale.com/hostname: "terraria"
spec:
  selector:
    game: terraria
  ports:
    - name: gate
      port: 80
      targetPort: 7777
      protocol: TCP
  loadBalancerClass: tailscale
  type: LoadBalancer
