name: Build and Publish Terraria container image

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf


      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract TERRARIA_VERSION from Dockerfile
        id: terraria_version
        run: |
          TERRARIA_VERSION=$(grep "ARG TERRARIA_VERSION" ./servers/terraria/image/Dockerfile | cut -d'=' -f2)
          echo "TERRARIA_VERSION=$TERRARIA_VERSION"
          echo "TERRARIA_VERSION=$TERRARIA_VERSION" >> $GITHUB_ENV

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./servers/terraria/image
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/terraria:v${{ env.TERRARIA_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
